[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Sverre Johann Bjørke <sverrejb@gmail.com>"]

[lib]
name = "mandelib"
path = "src/lib.rs"

[dependencies]
num = "0.1.41"
time = "*"
image = "0.10.1"
crossbeam = "0.3.2"